[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Environment variables should be set in Netlify dashboard
# Site settings > Environment variables
# Leave these empty to use the app's fallback demo mode

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200